### ISSUE TITLE
Impossible d'appeler le gestionnaire d'erreur de la méthode projet 'void'

### ISSUE THREAD

**Issue by Sieste68** [mesopelagique/Blame4D#4]
Project method 'void' is missing
<img width="627" alt="Capture d’écran 2021-05-11 à 15 13 17" src="https://user-images.githubusercontent.com/9090400/117821056-763ebd00-b26b-11eb-8a4a-6aaa23ed6c74.png">

**Comment by mesopelagique** [comment]
thanks

(if you use "Copier" for any bugs like that there is more information with full stack for dev, since version ... I do not know)

 my code use v19 theme to get font name and size used by method editor

I will catch and ignore and keep default size (do not want to take time to support older version)
